### Получить токен администратора Keycloak с scope=openid
POST http://localhost:8081/realms/master/protocol/openid-connect/token
Accept: application/json

client_id=admin-cli
&grant_type=password
&username=admin
&password=12345
&scope=openid

> {%
client.global.set("keycloak_admin_token_with_openid", response.body.access_token);
client.global.set("keycloak_refresh_token", response.body.refresh_token);
%}

###
POST http://localhost:8081/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli
&client_secret=AvAYzGmNXtqYSiWdHmhk1fvPjIDQxpq2
&grant_type=refresh_token
&refresh_token={{keycloak_refresh_token}}

### Получение реалмов
GET http://localhost:8081/admin/realms
Authorization: Bearer {{keycloak_admin_token_with_openid}}

### Получение информации о user
GET http://localhost:8081/realms/master/protocol/openid-connect/userinfo
Authorization: Bearer {{keycloak_admin_token_with_openid}}

### Создать пользователя в Keycloak (требует админские права)
POST http://localhost:8081/admin/realms/master/users
Content-Type: application/json
Authorization: Bearer {{keycloak_admin_token_with_openid}}

{
  "username": "user1",
  "email": "user11@example.com",
  "firstName": "Имя",
  "lastName": "Фамилия",
  "enabled": true,
  "credentials": [
    {
      "type": "password",
      "value": "пароль123",
      "temporary": false
    }
  ]
}

### Получение списка всех пользователей
GET http://localhost:8081/admin/realms/master/users
Authorization: Bearer {{keycloak_admin_token_with_openid}}
Content-Type: application/json

### Поиск пользователя по username (замените 'testuser' на нужное)
GET http://localhost:8081/admin/realms/master/users?username=user3
Authorization: Bearer {{keycloak_admin_token_with_openid}}
Content-Type: application/json

###удаление пользователя
DELETE http://localhost:8081/admin/realms/master/users/7aefa5b0-08ec-4d2b-8ef8-7d96dcecceef
Authorization: Bearer {{keycloak_admin_token_with_openid}}
