###  Auth and get token
POST http://localhost:8081/realms/resume/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=resume&
client_secret=AvAYzGmNXtqYSiWdHmhk1fvPjIDQxpq2&
grant_type=client_credentials&
scope=openid profile email

> {% client.global.set("auth_token", response.body.access_token); %}

### Get all promo codes with token
GET http://localhost:8000/employees
Authorization: Bearer {{auth_token}}
Accept: application/json

### Получение информации о user
GET http://localhost:8081/realms/resume/protocol/openid-connect/userinfo
Authorization: Bearer {{auth_token}}
